#ifndef  _DEFINITIONS_H_
#define  _DEFINITIONS_H_

#define TRANSITION_TIME 0.5
#define SPLASH_SCENE_TIME 2.0

#define PLAYER_COLLISION_BITMASK 0x0001
#define ENEMY_COLLISION_BITMASK 0x0010
#define BULLET_COLLISION_BITMASK 0x0100

#define GAME_OVER_BITMASK 0x0011
#define PLAYER_HIT_BITMASK 0x0110

#define PLAYER_SPEED 300.0
#define BACKGROUND_SPEED 200.0
#define FIGHTER_SPEED 300.0

#define BULLET_VELOCITY 500.0
#define PLAYER_GUN_RATE 0.1

#endif // _DEFINITIONS_H_
